---
- name: Ensure nginx conf file is installed
  template:
    src=../../templates/nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
  notify: restart nginx

- name: Ensure nginx default site file is installed
  template:
    src=../../templates/sites-available/default.j2
    dest=/etc/nginx/sites-available/default
    owner=root
    group=root
  notify: restart nginx
